sudo: required

language: minimal

services:
  - docker

before_install:
  - docker pull bottalk/cli
  
script:
  - pwd
  - for D in *; do [ -d "${D}" ] && [ "${D}" != "recipes" ] && echo "Working with dir: ${D}" && docker run --rm -v "/home/travis/build/bottalk/templates/${D}:/app" bottalk/cli --dir /app/ test; done
